### PR TITLE
Remove karma; Install BigTest cli

### PR DESCRIPTION
**Pull request by keathleydavidj**
This PR is to use bigtest cli instead of karma as the test runner in the countdown example app.

### CODE REVIEW

**Comment by wwilsman** [comment]
While we're installing the CLI, let's also use the [directory structure encouraged there](https://github.com/bigtestjs/cli/tree/master/templates/bigtest).

That way we can also move most of the CLI flags to the `bigtest.opts` file.

**Comment by keathleydavidj** [comment]
That's what I was missing, this does feel better.

**Review by wwilsman — APPROVED** [review]
:party-parrot:

**Comment by Robdel12** [comment]
Oh dang, I was hoping we could make this a different example. The blog post will now be pretty confusing to anyone coming here to see the code

**Comment by wwilsman** [comment]
That's true. We could change up the links in the post to point to the branch at the previous commit right before this PR

**Pull request merged**
